import { Poppins } from 'next/font/google';  // Import Poppins font
import './globals.css';

// Initialize Poppins font
const poppins = Poppins({
  weight: ['400', '600'],  // You can specify the weights you want
  subsets: ['latin'],  // Add subsets you need // CSS variable for applying the font
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
