import { Poppins } from "next/font/google"; // Import Poppins font
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

// Initialize Poppins font
const poppins = Poppins({
  weight: ["400", "600"], // You can specify the weights you want
  subsets: ["latin"], // Add subsets you need // CSS variable for applying the font
});

export const metadata = {
  title: "CSR Connect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased h-full`}>
        <Toaster />
        <main>{children}</main>
      </body>
    </html>
  );
}
